import './globals.css';
import { Poppins } from 'next/font/google';
import Link from 'next/link';

const poppins = Poppins({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: 'Maneesha',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <nav>
          <h1>Blogiees</h1>
          <Link href='/'>Home</Link>
          <Link href='/Blogs'>Blogs</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
