import './globals.css';
import { Poppins } from 'next/font/google';
import Link from 'next/link';

//components
import Navbar from './components/Navbar';

const poppins = Poppins({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: 'Maneesha',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
